#!/bin/bash

# Railway Link & Configure Script
# Run this manually in terminal

echo "🚂 Railway Configuration"
echo "========================"
echo ""
echo "STEP 1: Link projekat"
echo "Pokrenite ovu komandu i izaberite 'calm-ambition':"
echo ""
echo "  railway link"
echo ""
echo "Koristite strelice ↑↓ da izaberete 'calm-ambition' i pritisnite Enter"
echo ""
echo "---"
echo ""
echo "STEP 2: Provjerite status"
echo ""
echo "  railway status"
echo ""
echo "---"
echo ""
echo "STEP 3: Otvorite app u browseru"
echo ""
echo "  railway open"
echo ""
echo "---"
echo ""
echo "STEP 4: Pogledajte logove"
echo ""
echo "  railway logs"
echo ""
echo "---"
echo ""
echo "STEP 5: Redeploy (ako je potrebno)"
echo ""
echo "  railway up"
echo ""
echo "========================"
echo ""
echo "Vaš URL:"
echo "https://atomic-habits-production-ecee.up.railway.app"
